### ISSUE TITLE
Common Sense

### ISSUE THREAD

**Issue by vr8hub** [robinwhittleton/thomas-paine_essays#1]
- [x] Why the thead in the first table that's not displayed? It causes a noticeable additional gap between the text and the first table compared to the text and the second table. (See picture.) Later… I see you've done this in several places, so it's clearly intentional. But why?
- [x] I think if tabular-nums is used anywhere, it should be used everywhere. Otherwise, some of the columns use old style numbers, and some don't, and it looks off. (See picture again, first table.)
- [x] In the second table, the "Guns" column is right-justified, but in the first table it isn't. The scans show both right-justified, so they should probably be consistent.
- [ ] I know this matches the scans, but it looks odd to me that the "85" in the last row of the second table is at the top vertically, while the 2000 and 170,000 are centered vertically. Shouldn't that whole row be consistent? Could just be my OCD…
- [x] Are the _First_ and _Secondly_, etc., in the text really emphasis? I had those in the Federalist, and I just made them unsemanticated italics. We should probably be consistent, and I don't mind if it's me that needs to do a PR, but those don't strike me as (verbal) emphasis, more as just formatting.

![image](https://user-images.githubusercontent.com/19378955/115496681-cb208200-a22f-11eb-8844-99569091fdcb.jpeg)

**Comment by robinwhittleton** [comment]
Re the `visibility: collapse`, I’d added the semantic headings that aren’t in the scans for e.g. screenreader users, but was hiding them. Turns out though that although I was testing in browser (in my case Firefox), both Safari and Chrome don’t support the collapsing of whitespace here. So I’m going to make an editorial commit to always show them I think.

**Comment by robinwhittleton** [comment]
Re the vertical alignment, I can’t think of a good reason to not align with the scans here; I’m pretty sure I’ve seen this visual pattern in other tables in the corpus.

**Comment by vr8hub** [comment]
I don’t know why would a screenreader user would need the semantic headings any more than a non-screenreader user, but I agree that if they’re going to be there, they should be visible to everyone.
