### ISSUE TITLE
Decline and Fall…

### ISSUE THREAD

**Issue by vr8hub** [robinwhittleton/thomas-paine_essays#3]
- [ ] The dateline has a period after Germinal, should that be a comma?
- [ ] The side-by-side tables use ditto marks on the "millions", but the first table (the one before the side-by-side) don't use ditto marks on the "Expenses of the". Should they be consistent?

**Comment by robinwhittleton** [comment]
Re the period, that’s in the scans (I double-checked it too).

Added the ditto marks in the first table in https://github.com/robinwhittleton/thomas-paine_essays/commit/bc54eac28faea8e5aa0d5fb836c718d5d31af777.

**Comment by vr8hub** [comment]
Well, your decision, but I would consider the scans wrong. :)
